import "@/styles/globals.css";
import Navbar from "@/components/navbar";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Promptopia",
  description: "Generated by create next app",
};

import React from "react";

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <Providers>
        <body>
          <div className="main">
            <div className="gradient" />
          </div>

          <main className="app">
            <Navbar />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
};

export default RootLayout;
